### ISSUE TITLE
Deploy on PythonAnyware is down

### ISSUE THREAD

**Issue by Daniel-at-github** [freakboy3742/toga_web_demo#4]
Error message in http://freakboy3742.pythonanywhere.com/ : 

~~~
Developer info

Hi! If this is your PythonAnywhere-hosted site, then you're almost there — you just need to create a web app to handle this domain, freakboy3742.pythonanywhere.com. 
~~~

**Comment by freakboy3742** [comment]
Yes; the code for this project is now way out of date, so I let the deployment lapse. 

I'll put this repository into archive mode to reflect this fact.
